Global:
    login: user
    password: pass
    jump_server: jump.example.org
    ssh_port: 22
    use_sudo: false
    use_jump: true
    use_threads: true
    debug_level: error
    tunnel_port: 6666
    
Groups:
    solaris: 
    freebsd:
    linux:
    fs:
    web: 
    db:
    other:
